fos_elastica:
    clients:
        default: { host: elasticsearch, port: 9200 }
    indexes:
        app:
          types:
            user:
              mappings:
              persistence:
                # the driver can be orm, mongodb, phpcr or propel
                # listener and finder are not supported by
                # propel and should be removed
                driver: orm
                model: AppBundle\Entity\Post
                provider: ~
                listener: ~
                finder: ~
