fos_elastica:
    clients:
        default: { host: elasticsearch, port: 9200 }
    indexes:
        app:
          types:
            post:
              mappings:
                title: {type: string, boost: 3, fields: {raw: {type: string, index: not_analyzed}}}
                contentStrip: ~
              persistence:
                # the driver can be orm, mongodb, phpcr or propel
                # listener and finder are not supported by
                # propel and should be removed
                driver: orm
                model: AppBundle\Entity\Post
                provider: ~
                listener: ~
                finder: ~
